from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class DomainDefinition:
    id: str
    name: str
    core_keywords: tuple[str, ...]
    secondary_keywords: tuple[str, ...]
    strong_match_indicator: str


CORE_KEYWORD_WEIGHT = 1.0
SECONDARY_KEYWORD_WEIGHT = 0.45
STRONG_MATCH_MULTIPLIER = 1.15


HUMAIN_DOMAINS: tuple[DomainDefinition, ...] = (
    DomainDefinition(
        "ai_foundations",
        "AI Foundations & Core Methods",
        (
            "artificial intelligence",
            "machine learning",
            "deep learning",
            "neural networks",
            "neural network",
            "foundation models",
            "foundation model",
            "large language models",
            "large language model",
            "generative ai",
            "reinforcement learning",
            "supervised learning",
            "unsupervised learning",
            "self-supervised learning",
            "transfer learning",
            "representation learning",
            "bayesian learning",
            "probabilistic modeling",
            "causal inference",
            "causal machine learning",
            "optimization",
            "algorithm design",
            "graph neural networks",
            "natural language processing",
            "computer vision",
            "multimodal learning",
            "robotics",
            "autonomous systems",
            "planning",
            "reasoning",
            "agents",
            "agentic ai",
            "model evaluation",
            "model interpretability",
            "explainable ai",
            "alignment",
            "uncertainty quantification",
            "active learning",
            "federated learning",
            "privacy-preserving machine learning",
            "synthetic data",
        ),
        (
            "algorithms",
            "prediction",
            "classification",
            "clustering",
            "embeddings",
            "model architecture",
            "training data",
            "inference",
            "ai benchmarking",
            "evaluation metrics",
        ),
        "Developing, testing, adapting, or improving AI/ML methods rather than only applying existing tools.",
    ),
    DomainDefinition(
        "data_systems",
        "Data Systems & Infrastructure",
        (
            "data infrastructure",
            "data systems",
            "databases",
            "distributed systems",
            "cloud computing",
            "high-performance computing",
            "high performance computing",
            "data engineering",
            "data pipelines",
            "data pipeline",
            "data architecture",
            "data governance",
            "data integration",
            "data warehouse",
            "data lake",
            "apis",
            "interoperability",
            "metadata",
            "data standards",
            "data provenance",
            "data security",
            "cybersecurity",
            "privacy infrastructure",
            "scalable computing",
            "edge computing",
            "sensor networks",
            "internet of things",
            "geospatial data systems",
            "research computing",
            "platform engineering",
            "software engineering",
            "open-source tools",
            "computational infrastructure",
            "workflow automation",
            "reproducible computing",
            "mlops",
            "model deployment",
            "data visualization systems",
        ),
        (
            "large-scale datasets",
            "dashboards",
            "analytics platforms",
            "cloud resources",
            "data sharing",
            "secure environments",
            "compute resources",
            "data access",
            "digital infrastructure",
        ),
        "Enabling data collection, storage, movement, governance, computation, visualization, security, reproducibility, or deployment.",
    ),
    DomainDefinition(
        "human_ai",
        "Human-AI Interaction & Cognition",
        (
            "human-ai interaction",
            "human ai interaction",
            "human-computer interaction",
            "human computer interaction",
            "hci",
            "user experience",
            "ux",
            "interface design",
            "human-centered ai",
            "explainable ai",
            "ai trust",
            "trust calibration",
            "decision support",
            "cognitive science",
            "cognition",
            "behavioral science",
            "human behavior",
            "learning science",
            "education technology",
            "ai tutoring",
            "adaptive learning",
            "creativity",
            "design research",
            "participatory design",
            "user research",
            "usability",
            "human factors",
            "attention",
            "perception",
            "social interaction",
            "collaboration",
            "collective intelligence",
            "social computing",
            "virtual reality",
            "augmented reality",
            "mixed reality",
            "conversational agents",
            "chatbots",
            "recommender systems",
            "persuasive technology",
            "digital behavior",
            "mental models",
            "sensemaking",
        ),
        (
            "user study",
            "experiment",
            "interface",
            "workflow",
            "adoption",
            "engagement",
            "behavior change",
            "social dynamics",
            "group interaction",
            "team science",
        ),
        "How people understand, use, trust, resist, learn from, or collaborate with AI or digital systems.",
    ),
    DomainDefinition(
        "ai_science",
        "AI for Scientific Discovery",
        (
            "scientific discovery",
            "ai for science",
            "computational science",
            "simulation",
            "molecular discovery",
            "materials discovery",
            "drug discovery",
            "protein design",
            "genomics",
            "bioinformatics",
            "systems biology",
            "computational biology",
            "climate modeling",
            "earth systems",
            "physics-informed machine learning",
            "astronomy",
            "chemistry",
            "biology",
            "engineering design",
            "laboratory automation",
            "robotic lab",
            "high-throughput screening",
            "hypothesis generation",
            "experimental design",
            "inverse design",
            "digital twin",
            "scientific machine learning",
            "multi-omics",
            "imaging analysis",
            "microscopy",
            "remote sensing",
            "environmental modeling",
            "energy systems",
            "quantum computing",
            "computational chemistry",
            "materials science",
            "synthetic biology",
        ),
        (
            "discovery pipeline",
            "prediction of properties",
            "experiment optimization",
            "model-guided discovery",
            "data-driven science",
            "automated experimentation",
        ),
        "Using AI or data-intensive methods to generate hypotheses, design experiments, discover mechanisms, or accelerate science.",
    ),
    DomainDefinition(
        "ai_health_society",
        "AI for Health & Society",
        (
            "health ai",
            "clinical ai",
            "digital health",
            "public health",
            "precision medicine",
            "medical imaging",
            "electronic health records",
            "ehr",
            "clinical decision support",
            "patient monitoring",
            "mobile health",
            "mhealth",
            "wearable devices",
            "behavioral health",
            "mental health",
            "youth mental health",
            "epidemiology",
            "population health",
            "health equity",
            "social determinants of health",
            "health disparities",
            "implementation science",
            "care delivery",
            "hospital systems",
            "primary care",
            "community health",
            "global health",
            "nutrition",
            "physical activity",
            "sleep",
            "circadian rhythms",
            "environmental health",
            "education",
            "social policy",
            "criminal justice",
            "housing",
            "labor",
            "inequality",
            "poverty",
            "urban health",
            "social networks",
            "digital stress",
            "behavioral measurement",
        ),
        (
            "intervention",
            "trial",
            "patient outcomes",
            "risk prediction",
            "screening",
            "prevention",
            "surveillance",
            "community-based research",
            "health systems",
            "vulnerable populations",
            "youth",
            "families",
            "schools",
            "clinical populations",
        ),
        "Applying AI, data, or advanced measurement to health, social outcomes, public systems, equity, or community challenges.",
    ),
    DomainDefinition(
        "responsible_ai",
        "Responsible, Ethical & Policy AI",
        (
            "ai ethics",
            "responsible ai",
            "trustworthy ai",
            "ai governance",
            "ai policy",
            "algorithmic fairness",
            "algorithmic bias",
            "discrimination",
            "accountability",
            "transparency",
            "explainability",
            "interpretability",
            "ai safety",
            "ai alignment",
            "risk assessment",
            "audit",
            "impact assessment",
            "data privacy",
            "data protection",
            "surveillance",
            "civil rights",
            "human rights",
            "law and technology",
            "regulation",
            "compliance",
            "public policy",
            "technology policy",
            "platform governance",
            "misinformation",
            "disinformation",
            "content moderation",
            "democratic governance",
            "labor impacts",
            "social impacts",
            "equity",
            "justice",
            "consent",
            "data stewardship",
            "institutional review",
            "research ethics",
            "bias mitigation",
        ),
        (
            "fairness metrics",
            "ethical review",
            "legal framework",
            "policy design",
            "governance model",
            "public accountability",
            "safety standard",
            "auditability",
            "institutional risk",
            "regulatory pathway",
        ),
        "Examining how AI should be governed, evaluated, constrained, made fair, made safe, audited, regulated, or aligned with public values.",
    ),
    DomainDefinition(
        "ai_entrepreneurship",
        "AI Entrepreneurship & Translation",
        (
            "entrepreneurship",
            "innovation",
            "commercialization",
            "technology transfer",
            "startup",
            "venture",
            "product development",
            "prototype",
            "mvp",
            "translational research",
            "implementation",
            "deployment",
            "scaling",
            "adoption",
            "market validation",
            "business model",
            "go-to-market",
            "customer discovery",
            "intellectual property",
            "patent",
            "licensing",
            "venture capital",
            "accelerator",
            "incubator",
            "social entrepreneurship",
            "public-sector innovation",
            "clinical translation",
            "digital product",
            "platform",
            "applied ai",
            "ai product",
            "impact venture",
            "organizational change",
            "workforce adoption",
            "operational integration",
            "policy translation",
            "commercialization pathway",
        ),
        (
            "pilot",
            "proof of concept",
            "field test",
            "deployment partner",
            "user adoption",
            "sustainability",
            "business case",
            "scaling strategy",
            "product-market fit",
            "implementation partner",
        ),
        "Moving ideas, tools, algorithms, platforms, interventions, or policies into use beyond the lab.",
    ),
)

DOMAIN_BY_ID = {domain.id: domain for domain in HUMAIN_DOMAINS}

METHODOLOGICAL_TAG_KEYWORDS: dict[str, tuple[str, ...]] = {
    "machine_learning": ("machine learning", "deep learning", "neural networks"),
    "nlp": ("natural language processing", "nlp", "text mining"),
    "computer_vision": ("computer vision", "imaging analysis", "medical imaging"),
    "statistics": ("statistics", "statistical", "biostatistics", "probabilistic modeling"),
    "simulation": ("simulation", "computational model", "digital twin"),
    "qualitative_methods": ("qualitative", "ethnograph", "interview study", "user study"),
    "experimental": ("randomized", "clinical trial", "experiment", "trial"),
    "systems_building": ("software engineering", "platform engineering", "data engineering"),
}

APPLICATION_TAG_KEYWORDS: dict[str, tuple[str, ...]] = {
    "healthcare": ("health", "clinical", "medical", "patient", "public health"),
    "education": ("education", "learning science", "schools", "adaptive learning"),
    "climate": ("climate modeling", "environmental modeling", "earth systems"),
    "finance": ("finance", "financial", "banking", "investment"),
    "law_policy": ("law and technology", "legal framework", "regulation", "policy"),
    "governance": ("governance", "public policy", "civic", "platform governance"),
}

AI_ACTIVE_KEYWORDS = (
    "machine learning",
    "deep learning",
    "artificial intelligence",
    "neural networks",
    "neural network",
    "natural language processing",
    "computer vision",
    "large language models",
    "large language model",
    "generative ai",
    "reinforcement learning",
    "foundation models",
    "foundation model",
    "agentic ai",
)

AI_ADJACENT_KEYWORDS = (
    "data science",
    "computational",
    "informatics",
    "bioinformatics",
    "statistics",
    "statistical",
    "algorithm design",
    "modeling",
    "simulation",
    "digital health",
    "data engineering",
    "scientific machine learning",
)


def keyword_hits(text: str, keywords: tuple[str, ...]) -> int:
    return sum(1 for keyword in keywords if keyword in text)


def domain_raw_score(text: str, domain: DomainDefinition) -> float:
    core_hits = keyword_hits(text, domain.core_keywords)
    secondary_hits = keyword_hits(text, domain.secondary_keywords)
    score = core_hits * CORE_KEYWORD_WEIGHT + secondary_hits * SECONDARY_KEYWORD_WEIGHT
    if core_hits >= 2 or (core_hits >= 1 and secondary_hits >= 2):
        score *= STRONG_MATCH_MULTIPLIER
    return score
